server:
  port: 8080

spring:
  application:
    name: pc

  data:
    mongodb:
      host: mongo

eureka:
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/